

.Following this: https://github.com/osixia/docker-openldap#beginner-guide

.Fixes to run podman rootless:
----
sed -i '/driver/ s/overlay/vfs/' /home/$USER/.config/containers/storage.conf
rm /home/$USER/.local/share/containers/storage/libpod/bolt_state.db
sudo su - $USER
----

.Run the container
----
sudo podman run -p 389:389 -p 636:636 --name my-openldap-container --detach osixia/openldap:1.3.0
----

.Test a query from the same host
----
sudo podman exec my-openldap-container ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin
----
* -x = simple authentication
* -H = LDAP URI to bind to
* -b = The searchbase to use as a starting point for the search (omit to use the default)
* -D = The DN (Distinguished Name) to use to bind to the LDAP directory
* -w = Password for the entity specified with -D (can use -W to prompt for the password)

.Test a query from the CaaSPv4 Admin Node:
* Install the client software: `sudo zypper install openldap2-client`
* Test the query: `ldapsearch -x -H ldap://infra1.caaspv4.com -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin`
** Should return the same as on the localhost
** Query is fully dependent on correct Distinguished Names (DN), if the searchbase DN or user DN aren't correct, the query will fail

#### Move on to configure_dex.adoc to integrate CaaSPv4 with the LDAP server


// vim: set syntax=asciidoc:


