

.From k8s.io:
----
A RoleBinding may also reference a ClusterRole to grant the permissions to namespaced resources defined in the ClusterRole within the RoleBinding’s namespace. This allows administrators to define a set of common roles for the entire cluster, then reuse them within multiple namespaces.
----

.Creating new roles
* One way to get the right apiGroups, resources, and verbs correct is to review the output of `kubectl get clusterrole admin -o yaml  | less`
* Review the existing Roles: `kubectl get roles --all-namespaces`
* Review the existing ClusterRoles: `kubectl get clusterroles`

* Create a new rolebinding that references the LDAP group that encompasses the LDAP users that will access the namespace with admin priveliges
** Format is `kubectl create rolebinding <name of new rolebinding> -n <namespace> [--clusterrole=<name> | --role=<name>] [--group=<LDAP group name>] [--user=<LDAP user name>]`
----
kubectl create rolebinding admin-access -n kubeflow --clusterrole=admin --group=kubeflow-users
----

.For testing the basic LDAP container:
* Create a new rolebinding for the LDAP admin user:
----
kubectl create rolebinding admin-access -n default --clusterrole=admin --user=admin
----


.Update the oidc-dex-config configmap:
* `kubectl --namespace=kube-system edit configmap oidc-dex-config`
* Just need to update the connectors portion
* Good reference for what to update at: https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_integrate_external_ldap_tls
* Restart Dex and Gangway pods:
* `kubectl --namespace=kube-system delete pod -l app=oidc-dex`
* `kubectl --namespace=kube-system delete pod -l app=oidc-dex`

.Test authentication:
* `skuba auth login -s https://master.caaspv4.com:32000`
** Currently getting error: "F1120 11:26:42.346992   10908 login.go:88] error on login: auth failed: failed to query provider "https://master.caaspv4.com:32000": Get https://master.caaspv4.com:32000/.well-known/openid-configuration: x509: certificate signed by unknown authority"

 














// vim: set syntax=asciidoc:

