apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dirsrv
  name: dirsrv-internal-svc
spec:
  clusterIP: None
  ports:
  - name: dirsrv-nonsecure
    port: 3389
    protocol: TCP
    targetPort: 3389
  - name: dirsrv-secure
    port: 3636
    protocol: TCP
    targetPort: 3636
  selector:
    app: dirsrv
  type: ClusterIP
