apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dirsrv
  name: dirsrv-external-svc
spec:
  ports:
  - name: dirsrv-nonsecure
    port: 3389
    protocol: TCP
    targetPort: 3389
    nodePort: 30389
  - name: dirsrv-secure
    port: 3636
    protocol: TCP
    targetPort: 3636
    nodePort: 30636
  selector:
    app: dirsrv
  type: LoadBalancer
